controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

multi_auth:
    resource: "@MultiAuthBundle/Controller/"
    type: annotation
    